name: Build and push to ECR
on:
  push:
    branches: [main]
jobs:
  print-affected:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    outputs:
      affected_apps: ${{ steps.print-affected.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Print affected apps
        id: print-affected
        run: echo "::set-output name=affected_apps::$(npx nx print-affected -t build --select=projects)"
  api-build-and-push-to-ecr:
    runs-on: ubuntu-latest
    needs: print-affected
    if: ${{ contains(needs.print-affected.outputs.affected_apps, 'api') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install NPM dependencies
        run: npm ci
      - name: Build project
        run: npx nx build api
      - name: Build Docker image
        run: |
          docker build -f apps/api/Dockerfile . -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.API_ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.API_ECR_REPOSITORY }}:latest
  web-build-and-push-to-ecr:
    runs-on: ubuntu-latest
    needs: print-affected
    if: ${{ contains(needs.print-affected.outputs.affected_apps, 'web') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install NPM dependencies
        run: npm ci
      - name: Build project
        run: npx nx build web
      - name: Build Docker image
        run: |
          docker build -f apps/web/Dockerfile . -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.WEB_ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.WEB_ECR_REPOSITORY }}:latest
